### ISSUE TITLE
Uncaught TypeError: Cannot read property 'frequency' of undefined

### ISSUE THREAD

**Issue by noahwalugembe** [nstrayer/shinyearr#2]
I am this error when ever i try  the code  example 

Uncaught TypeError: Cannot read property 'frequency' of undefined
    at get_audio.average_freqs ((index):93)
    at get_audio.stopRecording ((index):89)
    at HTMLDivElement.<anonymous> ((index):135)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.v.handle (jquery.min.js:2)

![image](https://user-images.githubusercontent.com/27782388/67945125-37986300-fbef-11e9-8f4e-bdd4d27239dd.png)

**Comment by nstrayer** [comment]
Interesting! It looks like you are running the demo in Chrome, right? 

There's a tiny chance they recently changed the API I am using on the Javascript end. I will check it out.

**Comment by noahwalugembe** [comment]
even in opera it in not working dear. Which browser do you normally use

**Comment by noahwalugembe** [comment]
Hi @nstrayer am trying to go through the code but i cant fix it.

**Comment by nstrayer** [comment]
Hi @noahwalugembe , 

I just realized that this is in the old ShinyEarr repo and not the new Shinysense one! I should have put a depreciated message in this! 

Try out the function in Shinysense! http://nickstrayer.me/shinysense/ I have recently updated everything so it should be functioning with most browsers. Sorry for the confusion!

**Comment by noahwalugembe** [comment]
Have you updated the demo code in the repository. This is may first week in
r programming

**Comment by noahwalugembe** [comment]
Let me try to see if I can fix it if I successfully do it I will make a
Marge request on git. Please thanks for your response

**Comment by nstrayer** [comment]
I have updated the demo code for the `shiny_ear` function, yes! Check out the docs on running the demos http://nickstrayer.me/shinysense/reference/run_demo.html

**Comment by noahwalugembe** [comment]
Do I have to reinstall the package in studio

**Comment by noahwalugembe** [comment]
Thanks it is working now
